### ISSUE TITLE
Can't create container: manifest error

### ISSUE THREAD

**Issue by HannesS06** [ladral/qnap-nextcloud#11]
Hi, I (hope), I've followed the manual as close, as possible. When applying the content for the docker-compose.yml, I get a green tick after the checking, but the container isn't downloaded or applied.

I receive this error message:
"Failed to create application "next cloud": Error message: no matching manifest for linux/arm/v7 in the manifest list entries"

Any advice welcome.

Hannes

**Comment by ladral** [comment]
Hi @HannesS06 

It seams that Linuxservers have droped support for 32-bit architecture (armv7l) last year.

See: https://www.linuxserver.io/blog/a-farewell-to-arm-hf

**Comment by HannesS06** [comment]
Hello @ladral ,

I fear, you are right. That's it then. In several ways ;-). Thanks for the hint!

Hannes
