### ISSUE TITLE
Warning about 32-bit PHP, will this be an issue?

### ISSUE THREAD

**Issue by ogressel** [ladral/qnap-nextcloud#4]
First of all, this is an amazing project. Thank you so much for sharing this solution!

I recently got this warning message:
>It seems like you are running a 32-bit PHP version. Nextcloud needs 64-bit to run well. Please upgrade your OS and PHP to 64-bit! For further details read [the documentation page about this ↗](https://docs.nextcloud.com/server/25/go.php?to=admin-system-requirements).

Will this be an issue, and if yes, how can I update to 64-bit PHP?

**Comment by ladral** [comment]
Hi @ogressel 

The docker-compose file uses the linuxserver/nextcloud:latest image to build the nextcloud container. This should pull the correct image for your architecture. 

I guess the hardware you are using has a 32-bit architecture. I think Nextcloud just performs better on x86-64 architectures. 

The worst thing that could happen is, that Nextcloud drops support for 32-bit arch (not sure if they plan to). 
Good news, all your files are stored outside of the container (/share/Docker/nextcloud/data). So if Nextcloud (or linuxserver) drops support for 32-bit arch and you are not recieving updates for you Nextcloud instance, you should be able to get the data and migrate to another hardware.

**Comment by ogressel** [comment]
Thanks for your reply. It appears 32-bit support for NextCloud will indeed run out with the next major version. I am so used to everything being x86_64 that I did not realize my QNAP hardware was not.
